### ISSUE TITLE
rdkafka: SSL requirement

### ISSUE THREAD

**Issue by blindspotbounty** [swift-server/swift-kafka-client#123]
Currently, there is an implicit requirement to have openssl to build or use the library:
Possible build error:
```
In file included from /home/actions/_work/package-storage/package-storage/.build/checkouts/swift-kafka-client/Sources/Crdkafka/librdkafka/src/rdkafka_mock_handlers.c:34:
/home/actions/_work/package-storage/package-storage/.build/checkouts/swift-kafka-client/Sources/Crdkafka/librdkafka/src/rdkafka_int.h:55:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
```
Possible runtime error for compiled code:
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Termination Reason:    Namespace DYLD, Code 1 Library missing
```
Should OpenSSL library be statically linked or requirement explicitly mentioned in documentation?

**Comment by blindspotbounty** [comment]
Thank you for looking into it!

**Comment by blindspotbounty** [comment]
That would be nice to have all dependencies being able to statically compile, so that code would be possible compile and link for ios and other targets out of the box.

**Comment by blindspotbounty** [comment]
Hi @felixschlegel, @FranzBusch!
Could you advise if there are any updates on this issue, please?

**Comment by felixschlegel** [comment]
https://github.com/swift-server/swift-kafka-client/pull/135
