### ISSUE TITLE
Enable back pressure for KafkaConsumer

### ISSUE THREAD

**Issue by blindspotbounty** [swift-server/swift-kafka-client#131]
We performed some basic tests for consumer but with big number of records >11M
```
for try await record in consumer.messages {
    i = record.offset
    ctr += 1

    if ctr % 1000 == 0 {
        print("read up to \(i), ctr: \(ctr)")
    }
}
```
Unfortunately, without back pressure it leads to memory growth. For simplicity attaching screenshot:
![memgrow](https://github.com/swift-server/swift-kafka-client/assets/127803250/5976ae55-fb52-4e99-a3ce-64d9f4753150)

At some point, when all entries are read from kafka, memory usage is declining but would be nice if it would be possible to limit it with configuration (e.g. NIO HighLow watermark backpressure strategy).

PS: it seems that back pressure was removed around here https://github.com/swift-server/swift-kafka-client/pull/66

**Comment by blindspotbounty** [comment]
Just to compare that with even simple back pressure implementation (nio HighLowWatermark), memory go high:
![backpressure_enabled](https://github.com/swift-server/swift-kafka-client/assets/127803250/76dc08ba-8926-4938-b87e-e8d0805e2cb5)

**Comment by felixschlegel** [comment]
Since `librdkafka` is maintaining its own queue with fetched messages and we just read from that, applying back pressure to the `NIOAsyncSequence` in our code will not stop `librdkafka` from fetching more messages.

However, what we can do is find an elegant way to wrap `queued.min.messages` and `queued.max.messages.kbytes` (see [`CONFIGURATION.md`](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md) to allow for some back pressure.

**Comment by FranzBusch** [comment]
We should figure out what data is getting queued here and where it is queued. Is it inside rdkafka or inside SwiftKafka? My assumption was that the messages are actually buffered in our `AsyncSequence` and that's why rdkafka keeps on producing more.

**Comment by blindspotbounty** [comment]
Hi @felixschlegel and @FranzBusch, sorry for making you wait for the answer.
This case is related to swift-kafka-client and particularly to unbound `AsyncSequence`. Though, librdkafka have its own queue, it will stop requesting new data when it is full. Since it is configurable, it is possible to limit this queue.
Sorry that I missed providing the code, but basically I've used `NIOAsyncSequenceProducerBackPressureStrategies.HighLowWatermark(lowWatermark: 50, highWatermark: 100)` as a backpressure strategy. Plus added increased interval between polls (up to `max.poll.interval.ms`) in case queue is full. Since `NIOAsyncSequence` allows to produce even if it returns `.stopProducing` but with up to 5 minutes interval (default value of `max.poll.interval.ms`).
For sure, that is not perfect backpressure as we cannot avoid polling time to time but still make a lot of sense at application recovery when a lot of messages should be read.

**Comment by blindspotbounty** [comment]
@FranzBusch thank you for the brief excerpt. Sorry that I didn't provide it that way.
That sounds absolutely correct and dividing those queues should solve most of the problems except that anyway we should poll at least once per `max.poll.interval.ms` in consumer queue at least for one message to avoid silent client stop or provide some exception/error to downstream application (e.g. related to #110).

**Comment by felixschlegel** [comment]
Working on it!
