### ISSUE TITLE
Get Message body

### ISSUE THREAD

**Issue by Urkman** [swift-server/swift-kafka-client#167]
How can I get the body of the message.
I know, that it is in message.value as a ByteBuffer.
But how can I decode it? 

I'm all new to Kafka, so perhaps I need some tipps here :) 

Here is an Image of there message shown in KafkaUI...

<img width="866" alt="Bildschirmfoto 2024-06-17 um 16 39 34" src="https://github.com/swift-server/swift-kafka-client/assets/94297/aa6b5d01-0eec-473a-93e5-04dd33dacccd">

**Comment by FranzBusch** [comment]
It depends what is in your message. From a high level perspective the message is just a collection of bytes you need to know what the producer send. It could be JSON or protobuf or any other encoded format.

**Comment by Urkman** [comment]
Thanks, it is a Protobuf message :)
