### ISSUE TITLE
Redefine statistics callback

### ISSUE THREAD

**Issue by mr-swifter** [swift-server/swift-kafka-client#79]
`librdkafka` provides statistics over a callback which can be set using `rd_kafka_conf_set_stats_cb`.

Statistics callback should be set in combination with `statistics.interval.ms`.

Reference https://docs.confluent.io/platform/current/clients/librdkafka/html/md_STATISTICS.html

https://quicktype.io can be used to generate proper structs for statistics content.

**Comment by blindspotbounty** [comment]
@felixschlegel, @FranzBusch I have made some approach for this improvement.
Unfortunately, I have some doubts regarding ideas in the code, so could you give me a piece of advise in the PR, please?
